export { default as Dasbor } from './Dasbor';
export * from './akses';
export * from './audit';
export * from './gim';
export * from './interaksi';
export * from './kadi';
export * from './leksikon';
export * from './master';
export * from './wordnet';
export * from './artikel';